services:
  redis:
    image: redis:7-alpine
    container_name: ych_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: ych_web
    # Автоматизируем всё внутри контейнера при старте
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn profguide.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    ports:
      - "8000:8000"
    depends_on:
      - redis