# Generated by Django 6.0.5 on 2026-05-26 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название профессии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('salary_min', models.IntegerField(verbose_name='Мин. зарплата')),
                ('salary_max', models.IntegerField(verbose_name='Макс. зарплата')),
                ('demand_level', models.IntegerField(choices=[(1, 'Низкий спрос'), (2, 'Ниже среднего'), (3, 'Средний спрос'), (4, 'Выше среднего'), (5, 'Высокий спрос')], default=3, verbose_name='Востребованность')),
                ('image_url', models.URLField(blank=True, verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, verbose_name='Видео профессии')),
                ('universities', models.TextField(blank=True, help_text='Список вузов через запятую', verbose_name='Вузы')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('exam_type', models.CharField(choices=[('OGE', 'ОГЭ'), ('EGE', 'ЕГЭ')], max_length=3, verbose_name='Тип экзамена')),
                ('icon', models.CharField(default='📚', max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='#667eea', max_length=20, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_bot', models.BooleanField(default=False, verbose_name='От бота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.FloatField(default=1.0, verbose_name='Важность (0-2)')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'unique_together': {('profession', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='profession',
            name='required_subjects',
            field=models.ManyToManyField(through='core.ProfessionRequirement', to='core.subject', verbose_name='Требуемые предметы'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст задания')),
                ('correct_answer', models.CharField(max_length=20, verbose_name='Правильный ответ')),
                ('explanation', models.TextField(blank=True, verbose_name='Объяснение')),
                ('exam_year', models.IntegerField(default=2026, verbose_name='Год экзамена')),
                ('points', models.IntegerField(default=1, verbose_name='Баллы')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(9, '9 класс'), (10, '10 класс'), (11, '11 класс')], default=10, verbose_name='Класс')),
                ('school', models.CharField(blank=True, max_length=200, verbose_name='Школа')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('solved_at', models.DateTimeField(auto_now_add=True, verbose_name='Время решения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс пользователя',
                'verbose_name_plural': 'Прогресс пользователей',
                'unique_together': {('user', 'task')},
            },
        ),
    ]
