# Generated by Django 6.0.5 on 2026-05-27 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HollandQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('order', models.IntegerField(unique=True)),
                ('personality_type', models.CharField(choices=[('R', 'Реалистичный'), ('I', 'Интеллектуальный'), ('A', 'Артистичный'), ('S', 'Социальный'), ('E', 'Предприимчивый'), ('C', 'Конвенциональный')], max_length=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HollandTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('realistic_score', models.IntegerField(default=0)),
                ('investigative_score', models.IntegerField(default=0)),
                ('artistic_score', models.IntegerField(default=0)),
                ('social_score', models.IntegerField(default=0)),
                ('enterprising_score', models.IntegerField(default=0)),
                ('conventional_score', models.IntegerField(default=0)),
                ('primary_type', models.CharField(blank=True, choices=[('R', 'Реалистичный'), ('I', 'Интеллектуальный'), ('A', 'Артистичный'), ('S', 'Социальный'), ('E', 'Предприимчивый'), ('C', 'Конвенциональный')], max_length=1)),
                ('secondary_type', models.CharField(blank=True, choices=[('R', 'Реалистичный'), ('I', 'Интеллектуальный'), ('A', 'Артистичный'), ('S', 'Социальный'), ('E', 'Предприимчивый'), ('C', 'Конвенциональный')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holland_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_taken'],
            },
        ),
    ]
